import { Cormorant_Upright, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const CormorantUpright = Cormorant_Upright({
  variable: "--font-Cormorant_Upright",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const OpenSans = Open_Sans({
  variable: "--font-Open_Sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${CormorantUpright.variable} ${OpenSans.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
